version: "3.4"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
    ports:
      - 8080:8080
    logging:
      driver: none

  worker:
    build: .
    volumes:
      - ./worker/main.js:/worker/main.js
      - ./docs:/worker/docs
    environment:
      REDIS_URL: redis://redis
    entrypoint: nodemon main.js
    scale: 1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    logging:
      driver: none
